import { Menu } from "@/components/menu";
import { ThemeToggle } from "@/components/theme-toggle";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="py-2 bg-muted sticky top-0 z-10 overflow-hidden border-b">
          <nav className="flex items-center justify-between max-w-screen-lg h-full mx-auto">
            <Menu />
            <ThemeToggle />
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
